HelpMap/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from HelpMap import settings
from registration import views as regviews
from map import views as mapviews
from social import views as socialviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mapviews.index, name="index"),
    path('account/login/', regviews.do_login, name="login"),
    path('account/register/', regviews.do_register, name="register"),
    path('account/logout/', regviews.do_logout, name="logout"),
    path('info/', mapviews.get_info, name="who"),
    path('offer/<int:offer_id>/', mapviews.show_help_point, name="offer"),
    path('map/', mapviews.show_map, name="map"),
    path('map/offer_help/', mapviews.new_help_point, name="add-point"),
    path('map/delete/<int:point_id>', mapviews.delete_help_point, name="delete-point"),
    path('messages/', socialviews.show_messages, name="received-messages"),
    path('messages/<int:user_id>/', socialviews.message_handler, name="conversation"),
    path('profile/', socialviews.show_profile, name="profile"),
    path('profile/<int:user_id>', socialviews.show_other_profile, name="other-profile"),
    path('profile/change/', regviews.change_profile, name="change-profile"),
    path('api/messages/<int:user_id>', socialviews.get_messages_rest, name="api"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

map/models.py
from django.db import models
from djgeojson.fields import *
from djgeojson.fields import PointField
from django.contrib.auth.models import User


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=40)

    def __str__(self):
        return f"{self.title}"


class HelpPoint(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=2000)
    geom = PointField(default="{'type': 'Point', 'coordinates': [0, 0]}")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"

    @property
    def popupContent(self):
        content = f"""
            <img src="{self.author.profile.picture.url}" style="width: 50px; height: 50px;"/><br/>
            <strong>{self.title}</strong> von <a href='/profile/{self.author.id}'>{self.author}</a><br/>
            <a href='/offer/{self.id}'>Zum Angebot</a>
        """
        return content

map/forms.py
from django import forms
from map.models import *


class NewHelpPointForm(forms.Form):
    title = forms.CharField(label="Titel", widget=forms.TextInput(attrs={'placeholder': 'Titel Ihres Angebotes*'}))
    description = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Beschreibung*', 'rows': '8'}))
    category = forms.ModelChoiceField(queryset=Category.objects.all(), label="Kategorie*")
    location = forms.CharField(label="", widget=forms.Textarea(attrs={'placeholder': 'Standort', 'hidden': 'true'})
                               , max_length=20000)

map/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import render
from django.contrib import messages
from map.forms import *
from map.models import *
from social.views import show_profile


def index(request):
    context = {
        "page_title": "Startseite"
    }
    return render(request, "index.html", context)


def show_map(request):
    help_points = HelpPoint.objects.all()
    context = {
        "page_title": "Karte",
        "help_points": help_points,
    }
    return render(request, "map/map.html", context)


@login_required(redirect_field_name='next', login_url="/account/login")
def new_help_point(request):
    html_file = "map/add_help_point.html"
    context = {"page_title": "Hilfe anbieten"}
    if request.method == "POST":
        form = NewHelpPointForm(request.POST)
        if form.is_valid():
            try:
                title = form.cleaned_data.get("title")
                description = form.cleaned_data.get("description")
                category = Category.objects.all().filter(title=form.cleaned_data.get("category"))[0]
                point = form.cleaned_data.get("location")
                if point is None:
                    messages.add_message(request, messages.ERROR, "Standort fehlerhaft!")
                    context["form"] = form
                    return render(request, html_file, context)
                point_list = point.split(",")
                map_point = {
                    'type': 'Point',
                    'coordinates': [point_list[1], point_list[0]]
                }

                new_point = HelpPoint(author=request.user, title=title, description=description, geom=map_point,
                                      category=category)
                new_point.save()
                context["form"] = form
                messages.add_message(request, messages.SUCCESS, "Der Punkt wurde der Karte hinzugefügt")
                return render(request, html_file, context)

            except Exception as e:
                messages.add_message(request, messages.ERROR, e)
                context["form"] = form
        else:
            messages.add_message(request, messages.ERROR,
                                 "Bitte füllen Sie alle Felder aus und wählen Sie einen Standort!")
            context["form"] = form
    else:
        form = NewHelpPointForm()
        context["form"] = form
        return render(request, html_file, context)
    return render(request, html_file, context)


def show_help_point(request, offer_id):
    html_file = "map/help_point_single.html"
    try:
        help_point = HelpPoint.objects.get(id=offer_id)
    except HelpPoint.DoesNotExist:
        raise Http404("Der Helppoint ist aktuell nicht verfügbar.")

    context = {
        "page_title": help_point.title,
        "help_point": help_point
    }
    return render(request, html_file, context)


@login_required(redirect_field_name='next', login_url="/account/login")
def delete_help_point(request, point_id):
    try:
        help_point = HelpPoint.objects.get(id=point_id)
        if help_point.author == request.user:
            help_point.delete()
            messages.add_message(request, messages.SUCCESS, "Das Angebot wurde gelöscht")
        else:
            messages.add_message(request, messages.ERROR,
                                 "Sie können nur die mit Ihrem Nutzerkonto verknüpften Angebote löschen.")
    except Exception:
        messages.add_message(request, messages.ERROR, "Leider ist beim Löschen ein Fehler aufgetreten.")
    return show_profile(request)


def get_info(request):
    context = {"page_title": "Info"}
    return render(request, "info.html", context)

templates/map/add_help_point.html
{% include "base/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="container" style="margin-bottom: 20px">
            <h1 style="margin-bottom: 10px">Hilfe anbieten</h1><br>
            <h2>Eckdaten zu Ihrem Angebot</h2>
        <form method="post">
        {% bootstrap_messages %}
        {% csrf_token %}
            <div class="row">
                <div class="col">
                            {% bootstrap_field form.title %}
                </div>
                <div class="col">
                            {% bootstrap_field form.category %}
                </div>
            </div>
        {% bootstrap_field form.description %}
             <input type="hidden" name="location" maxlength="63" class="form-control loc-field" placeholder="Pick a location on map below" title="" required="" id="id_location" readonly="">
            <h2>Auswahl des Standortes</h2>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"></script>
            <style>
	body { margin: 0; padding: 0; }
	#map {
        top: 0;
        bottom: 0;
        width: 100%;
        overflow: hidden;
        height: 350px;
    }

    .mapboxgl-ctrl-geocoder {
        min-width: 400px!important;
    }

};
</style>
<link
rel="stylesheet"
href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css"
type="text/css"
/>
<!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
<div id="map"></div>

<script>
	mapboxgl.accessToken = '{{ mapbox_api_key }}';


if (!mapboxgl.supported()) {
    alert('Ihr Browser unterstützt diese Version MapboxGL leider nicht.');
} else {
    $(document).ready(function () {
        var coordinatesGeocoder = function (query) {
            var matches = query.match(/^[ ]*(?:Lat: )?(-?\d+\.?\d*)[, ]+(?:Lng: )?(-?\d+\.?\d*)[ ]*$/i);
            if (!matches) {
                return null;
            }

            function coordinateFeature(lng, lat) {
                return {
                    center: [lng, lat],
                    geometry: {
                        type: "Point",
                        coordinates: [lng, lat]
                    },
                    place_name: 'Lat: ' + lat + ' Lng: ' + lng, // eslint-disable-line camelcase
                    place_type: ['coordinate'], // eslint-disable-line camelcase
                    properties: {},
                    type: 'Feature'
                };
            }

            var coord1 = Number(matches[1]);
            var coord2 = Number(matches[2]);
            var geocodes = [];

            if (coord1 < -90 || coord1 > 90) {
            // must be lng, lat
                geocodes.push(coordinateFeature(coord1, coord2));
            }

            if (coord2 < -90 || coord2 > 90) {
            // must be lat, lng
                geocodes.push(coordinateFeature(coord2, coord1));
            }

            if (geocodes.length === 0) {
            // else could be either lng, lat or lat, lng
                geocodes.push(coordinateFeature(coord1, coord2));
                geocodes.push(coordinateFeature(coord2, coord1));
            }

            return geocodes;
        };

        function translate_to_string(obj) {
            var lat = obj.lat;
            var lng = obj.lng;
            return lng + "," + lat
        }

        function translate_to_reversed_string(obj) {
            var lat = obj.lat;
            var lng = obj.lng;
            return lat + "," + lng
        }

        function replace_order(array) {
            return [array[1], array[0]]
        }

        var input = $(".loc-field");
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [13.38333, 52.51667],
            zoom: 9
        });
        var map_attr_center = [13.38333, 52.51667];
        if (input.val()) {
            var marker = new mapboxgl.Marker({draggable: false, color: "red",});
            marker.setLngLat(map_attr_center)
                .addTo(map);
            input.val(replace_order(map_attr_center));
        }

        var geocoder = new MapboxGeocoder({
            accessToken: mapboxgl.accessToken,
            mapboxgl: mapboxgl,
            bbox: [12.639771,52.113252,13.985596,52.835958],
            localGeocoder: coordinatesGeocoder,

        });
        var map_attr_rotate = true;
        var map_attr_geocoder = true;
        var map_attr_fullscreen_button = false;
        var map_attr_navigation_buttons = true;
        var map_attr_marker_color = "red";
        map.getCanvas().style.cursor = "pointer";
        if (!map_attr_rotate) {
            map.dragRotate.disable();
            map.touchZoomRotate.disableRotation();
        }
        var map_attr_track_location_button = true;
        if (map_attr_track_location_button) {
            map.addControl(new mapboxgl.GeolocateControl({
                positionOptions: {
                    enableHighAccuracy: true
                },
                trackUserLocation: true,
            }));
        }
        if (map_attr_geocoder) {
            map.addControl(geocoder, "top-left");
        }

        if (map_attr_fullscreen_button) {
            map.addControl(new mapboxgl.FullscreenControl());
        }
        if (map_attr_navigation_buttons) {
            map.addControl(new mapboxgl.NavigationControl());
        }
        geocoder.on("result", function (e) {
            $("div.mapboxgl-marker.mapboxgl-marker-anchor-center").not(".mapboxgl-user-location-dot").remove();
            input.val(replace_order(e.result.geometry.coordinates));
            var marker = new mapboxgl.Marker({draggable: false, color: map_attr_marker_color,});
            marker.setLngLat(e.result.geometry.coordinates)
                .addTo(map);

            $(document).trigger("reverse-geocode", [e.result.place_name,])
        });

        map.on("click", function (e) {
            $("div.mapboxgl-marker.mapboxgl-marker-anchor-center").not(".mapboxgl-user-location-dot").remove();
            input.val(translate_to_reversed_string(e.lngLat));
            var marker = new mapboxgl.Marker({draggable: false, color: map_attr_marker_color,});
            marker.setLngLat(e.lngLat)
                .addTo(map);


        });

    });
}
</script>
                <script>
    $(document).on("reverse-geocode", function (e, input) {
    $("#secret-id-address-mapbox-location-field").val(input);
});
    </script>
            <div class="row" style="margin-top: 20px">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary">Neuen Helppoint eintragen</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/map/add_help_point_success.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title }} | {{ project_title }}</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{{ custom_css }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@100;400;700&family=Roboto&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/5926ae8c15.js" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% bootstrap_javascript %}
</head>
<script>
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
<body>
{% block header %}
    <header class="bg-gradient-primary-to-secondary">
    {% include "base/nav.html" %}
    <div class="container">
        {%  include "base/messages.html" %}
        <div class="text-middle gate-layer">
        <h1 class="introtext">Vielen Dank für Ihre Mithilfe.</h1>
            <p class="plain">Gemeinsam für Berlin.</p>
            </div>
    </div>
           {% include "base/wave.html" %}
    </header>

{% endblock %}
{% block content %}

{% endblock %}
</body>
</html>

templates/map/help_point_single.html
{% include "base/base.html" %}

{% block content %}
    <div class="container">
        <p><a href="{% url 'map' %}">← Zurück zur Karte</a></p>
  <div class="row">
      <div class="col">
        <h1 class="singleview">{{ help_point.title }}</h1>
          <strong><p>Kategorie:</strong> {{ help_point.category }} | <strong>User:</strong> <a href="{% url 'other-profile' user_id=help_point.author_id %}">{{ help_point.author }}</a></p>
          <a class="btn-primary btn" href="{% url 'conversation' user_id=help_point.author_id %}">Anbieter kontaktieren</a><br><br>
          <h2>Beschreibung</h2>
        <p>{{ help_point.description }}</p>
      </div>
    <div class="col">
        <h2>Karte</h2>
       <div id='map' style='width: 400px; height: 300px;'></div>
<script>
// TO MAKE THE MAP APPEAR YOU MUST
// ADD YOUR ACCESS TOKEN FROM
// https://account.mapbox.com
mapboxgl.accessToken = '{{ mapbox_api_key }}';
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
center: [{{help_point.geom.coordinates.0 }},{{ help_point.geom.coordinates.1 }}], // starting position [lng, lat]
zoom: 14 // starting zoom
});

var marker = new mapboxgl.Marker()
.setLngLat([{{help_point.geom.coordinates.0 }},{{ help_point.geom.coordinates.1 }}])
.addTo(map);
</script>
  </div>
</div>
{% endblock %}

templates/map/map.html
{% extends "base/base.html" %}
{% load geojson_tags %}


{% block content %}
    <style>
    .mapboxgl-popup {
    max-width: 400px;
    font-family: 'Roboto', sans-serif;
    }

    .mapboxgl-canvas-container {

    }

    .mapholder {
        position: relative;
        height: 70% !important;
        width: 100% !important;
        margin-bottom: 25px;
    }
    #map {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 100%;
    height: 100%;
    }


        .point-6 {
        width: 25px;
        height: 25px;
        border-radius: 50%;
        border:1px solid gray;
        background-color: black;
    }

    .filter-group {
    font-family: 'Barlow Condensed', sans-serif;
    font-size: 20px;
    font-weight: 400;
    position: absolute;
    top: 10px;
    left: 10px;
    z-index: 1;
    border-radius: 3px;
    width: 150px;
    color: #FFD0A5;
}

.filter-group input[type='checkbox']:first-child + label {
border-radius: 3px 3px 0 0;
}

.filter-group label:last-child {
border-radius: 0 0 3px 3px;
border: none;
}

.filter-group input[type='checkbox'] {
display: none;
}

.filter-group input[type='checkbox'] + label {
background-color: #374B73;
display: block;
cursor: pointer;
padding: 10px;
border-bottom: 1px solid rgba(0, 0, 0, 0.25);
}

.filter-group input[type='checkbox'] + label {
background-color: #374B73;
text-transform: capitalize;
}

.filter-group input[type='checkbox'] + label:hover {
background-color: #FFD0A5;
    color: #374B73;
}

.filter-group input[type='checkbox']:checked + label:before {
content: '✔';
margin-right: 5px;
}
    </style>
    <div class="container"><h1>Karte</h1>{% include 'base/messages.html' %}</div>
    <section class="container mapholder">
    <div id="map"></div>
        <nav id="filter-group" class="filter-group"></nav>
<script>
const categories = { 1: "Verschenken", 2: "Einkaufshilfe", 3: "Homeschooling", 4: "Helfende Hände", 5: "Studentenjobs", 6: "Mitfahrzentrale" };
const category_counter = Object.keys(categories).length;
mapboxgl.accessToken = '{{ mapbox_api_key }}';
var filterGroup = document.getElementById('filter-group');
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
center: [13.38333, 52.51667],
zoom: 10
});

function toReadableString(id) {
    return categories[id];
}

const images =[
    {url: '/static/map/icon-1.png', id: 'icon-1'},
    {url: '/static/map/icon-2.png', id: 'icon-2'},
    {url: '/static/map/icon-3.png', id: 'icon-3'},
    {url: '/static/map/icon-4.png', id: 'icon-4'},
    {url: '/static/map/icon-5.png', id: 'icon-5'},
    {url: '/static/map/icon-6.png', id: 'icon-6'}
];

images.forEach(img => {
    map.loadImage(img.url, function(error, res) {
      map.addImage(img.id, res)
    })
});

map.on('load', function () {
    map.resize();
});

// Add zoom and rotation controls to the map.
map.addControl(new mapboxgl.NavigationControl());
map.addControl(new mapboxgl.GeolocateControl({
    positionOptions: {
        enableHighAccuracy: true
    },
        trackUserLocation: true
}));

// Set viewport to users location
navigator.geolocation.getCurrentPosition(position => {
                this.center = [position.coords.latitude, position.coords.longitude]
            });

var collection = {{ help_points|geojsonfeature:"popupContent,category"|safe }};
var geojson = collection;
var markerHeight = 50, markerRadius = 10, linearOffset = 25;
var popupOffsets = {
'top': [0, 0],
'top-left': [0,0],
'top-right': [0,0],
'bottom': [0, -markerHeight],
'bottom-left': [linearOffset, (markerHeight - markerRadius + linearOffset) * -1],
'bottom-right': [-linearOffset, (markerHeight - markerRadius + linearOffset) * -1],
'left': [markerRadius, (markerHeight - markerRadius) * -1],
'right': [-markerRadius, (markerHeight - markerRadius) * -1]
};

var layerIdCollection = [];

map.on('load', function() {
// Add a GeoJSON source containing place coordinates and information.
map.addSource('places', {
'type': 'geojson',
'data': geojson
});

collection.features.forEach(function(feature) {
var symbol = feature.properties['category'];
var layerID = 'marker-' + symbol;
layerIdCollection.push(layerID);

// Add a layer for this symbol type if it hasn't been added already.
if (!map.getLayer(layerID)) {
map.addLayer({
'id': layerID,
'type': 'symbol',
'source': 'places',
'layout': {
    'icon-image': 'icon-' + symbol,
    'icon-allow-overlap': true,
}, 'filter': ['==', 'category', symbol]
});

// Add checkbox and label elements for the layer.
var input = document.createElement('input');
input.type = 'checkbox';
input.id = layerID;
input.checked = true;
filterGroup.appendChild(input);

var label = document.createElement('label');
label.setAttribute('for', layerID);
label.textContent = toReadableString(symbol);
filterGroup.appendChild(label);

// When the checkbox changes, update the visibility of the layer.
input.addEventListener('change', function(e) {
map.setLayoutProperty(
layerID,
'visibility',
e.target.checked ? 'visible' : 'none'
);
});
}
});
});

        map.on('click', function (e) {


            var features = map.queryRenderedFeatures(e.point, { layers: layerIdCollection });
            console.log(features);

            if (!features.length) {
                return;
            }

            var feature = features[0];

            // Populate the popup and set its coordinates
            // based on the feature found.
            var popup = new mapboxgl.Popup()
                .setLngLat(feature.geometry.coordinates)
                .setHTML(feature.properties.popupContent)
                .addTo(map);
        });

        // Use the same approach as above to indicate that the symbols are clickable
        // by changing the cursor style to 'pointer'.
        map.on('mousemove', function (e) {
                //console.log(id);
            var features = map.queryRenderedFeatures(e.point, { layers: layerIdCollection });
            map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
        });

</script>
        </section>
{% endblock %}
<footer>2020 | Berlin hilft | Objektorientierte Skriptsprachen SoSe 2020</footer>